%% PAPER 1 - POST-HELD-OUT NOISE STRESS PREFLIGHT v1.0
% ZERO-NOISE CODE-PARITY CHECK ONLY. No COMSOL and no new scientific result.
clear; clc;

fprintf('\n============================================================\n');
fprintf(' PAPER 1 - POST-HELD-OUT NOISE PREFLIGHT v1.0\n');
fprintf(' ZERO-NOISE PARITY CHECK | NO COMSOL\n');
fprintf('============================================================\n\n');

script_dir=fileparts(mfilename('fullpath'));
stage_root=fileparts(script_dir); % 09_... if script is in 01_RUN
workspace_root=stage_root;
while ~exist(fullfile(workspace_root,'01_COMSOL_FEM'),'dir')
    parent=fileparts(workspace_root);
    if strcmp(parent,workspace_root), error('Could not locate Paper 1 workspace root.'); end
    workspace_root=parent;
end

protocol_dir=fullfile(stage_root,'00_PROTOCOL');
protocol_file=fullfile(protocol_dir,'POST_HELDOUT_NOISE_PROTOCOL_v10.json');
if ~exist(protocol_file,'file'), error('Missing frozen protocol: %s',protocol_file); end
cfg=jsondecode(fileread(protocol_file));
assert(strcmp(cfg.status,'FROZEN BEFORE MEASUREMENT-NOISE STRESS RESULTS'));

final_root=fullfile(workspace_root,'05_HeldOut84_FINAL_DO_NOT_TOUCH','FINAL_v5M80_N15');
fem_dir=fullfile(final_root,'02_FEM_RESULTS_FROZEN_v12');
final_results=fullfile(final_root,'04_FINAL_RESULTS');

checkpoints=[6 8 10 15].';
initial_xy=[12 2;4 12;-8 10;-12 -2;-4 -12;8 -10];
parity_ids=double(cfg.preflight.parity_case_ids(:));
tol=double(cfg.preflight.parity_numeric_tolerance);
vars={'L_hat_m','phi_hat_deg','d_hat_m','endpoint_error_m','d_abs_error_m','phi_abs_error_deg','fullfield_RMSE_pct_RMS'};

for ii=1:numel(parity_ids)
    c=parity_ids(ii);
    f=fullfile(fem_dir,sprintf('case_%03d_surface_potential_FROZEN_v12.csv',c));
    assert(exist(f,'file')==2,'Missing FEM case %d',c);
    T=readtable(f);
    assert(height(T)==956 && all(isfinite(T.V_fem_V)),'Invalid FEM case %d',c);
    P=[T.x_m T.y_m]; V=T.V_fem_V;
    truth.L=T.L_true_m(1); truth.phi=mod(T.phi_true_deg(1),360);
    truth.d=T.d_true_m(1); truth.rho=T.rho_true_ohm_m(1); truth.I=T.Iinj_A(1);
    if ismember('run_order_col',T.Properties.VariableNames), run_order=T.run_order_col(1); else, run_order=ii; end

    O=paper1_v5M80_noise_task_v10(P,V,V,truth,run_order,c,initial_xy,checkpoints);
    A0=readtable(fullfile(final_results,sprintf('case_%03d_active_checkpoints.csv',c)));
    S0=readtable(fullfile(final_results,sprintf('case_%03d_space_checkpoints.csv',c)));
    AS0=readtable(fullfile(final_results,sprintf('case_%03d_active_selection.csv',c)));
    SS0=readtable(fullfile(final_results,sprintf('case_%03d_space_selection.csv',c)));

    assert(isequal(O.active.n,A0.n) && isequal(O.space.n,S0.n),'Checkpoint mismatch case %d',c);
    maxdiff=0;
    for j=1:numel(vars)
        vn=vars{j};
        maxdiff=max(maxdiff,max(abs(O.active.(vn)-A0.(vn))));
        maxdiff=max(maxdiff,max(abs(O.space.(vn)-S0.(vn))));
    end
    assert(maxdiff<=tol,'Numeric parity FAIL case %d: max diff %.3g > %.3g',c,maxdiff,tol);
    assert(isequal(O.active_selection.selected_index,AS0.selected_index),'Active path parity FAIL case %d',c);
    assert(isequal(O.space_selection.selected_index,SS0.selected_index),'Space path parity FAIL case %d',c);
    fprintf('case %3d: PASS | max numeric delta = %.3g | paths exact\n',c,maxdiff);
end

pass_file=fullfile(protocol_dir,'NOISE_STRESS_PREFLIGHT_PASS.txt');
fid=fopen(pass_file,'w');
fprintf(fid,'POST-HELD-OUT NOISE STRESS PREFLIGHT PASS\n');
fprintf(fid,'Protocol: %s\n',cfg.protocol_version);
fprintf(fid,'Parity cases: %s\n',mat2str(parity_ids.'));
fprintf(fid,'Tolerance: %.3g\n',tol);
fprintf(fid,'Zero-noise frozen outputs reproduced before noisy execution.\n');
fclose(fid);

fprintf('\nPREFLIGHT PASS. Sentinel written to:\n%s\n',pass_file);
fprintf('No measurement-noise result has been generated by this preflight.\n');
